USE DATABASE DOLPHIN_MOVIELENS_DB;
USE SCHEMA DOLPHIN_MOVIELENS_DB.PUBLIC;

-- Top 10 Most Popular (ratings count) Movies
SELECT DM.TITLE AS MOVIE,
    COUNT(FR.RATING) AS RATINGS_COUNT,
    AVG(FR.RATING) AS AVERAGE_RATING
FROM FACT_RATINGS FR
JOIN DIM_MOVIES DM ON FR.MOVIE_ID = DM.ID
GROUP BY DM.TITLE
ORDER BY RATINGs_count DESC
LIMIT 10;

-- Top 10 Most Rated (raiting values)  Movies
SELECT DM.TITLE AS MOVIE,
    AVG(FR.RATING) AS AVG_RATINGS
FROM FACT_RATINGS FR
JOIN DIM_MOVIES DM ON FR.MOVIE_ID = DM.ID
GROUP BY DM.TITLE
ORDER BY AVG_RATINGS DESC
LIMIT 10;

-- Distribution of how often M rate movies compared to F
SELECT DU.GENDER, COUNT(DU.GENDER)
FROM FACT_RATINGS FR
JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID
JOIN DIM_MOVIES DM ON FR.MOVIE_ID = DM.ID
GROUP BY DU.GENDER

-- Ratings count by ocupation
-- Shows people with what ocupation are more active and rates movies the most
SELECT 
    DU.Occupation AS Occupation, 
    COUNT(FR.RATING) AS CNT_RATING 
FROM FACT_RATINGS FR
JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID
GROUP BY DU.Occupation
ORDER BY CNT_RATING DESC
LIMIT 5;

-- Frequency of Movie Ratings by Gender
SELECT 
    DU.AGE_GROUP AS AGE_RANGE, 
    COUNT(FR.RATING) AS CNT_RATING 
FROM FACT_RATINGS FR
JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID
GROUP BY DU.AGE_GROUP 
ORDER BY AGE_RANGE



-- Average ratings by genres
SELECT 
    GENRE_NAME, 
    AVG_RATING 
FROM PUBLIC.RATINGS_BY_GENRE_VIEW
ORDER BY AVG_RATING DESC

-- 5 most rated genres
SELECT 
    GENRE_NAME, 
    CNT_RATING 
FROM PUBLIC.RATINGS_BY_GENRE_VIEW
ORDER BY CNT_RATING DESC
LIMIT 5;


-- Ratings by YEAR
SELECT d.YEAR AS YEAR, COUNT(f.RATING) AS CNT_RATINGS
FROM FACT_RATINGS f
JOIN DIM_DATES d ON f.RATING_DATE = d.DDATE
GROUP BY d.YEAR
ORDER BY CNT_RATINGS DESC;

-- Ratings by MONTH
SELECT d.MONTH_NAME AS MONTH_NAME, COUNT(f.RATING) AS CNT_RATINGS
FROM FACT_RATINGS f
JOIN DIM_DATES d ON f.RATING_DATE = d.DDATE
GROUP BY d.MONTH_NAME
ORDER BY CNT_RATINGS DESC;


-- popularity of genres by gender
SELECT 
    GENRE_NAME, 
    MAX(CASE WHEN Gender = 'M' THEN CNT_GENDER END) AS CNT_RATINGS_M,
    MAX(CASE WHEN Gender = 'F' THEN CNT_GENDER END) AS CNT_RATINGS_F
FROM(
    SELECT 'Action'      AS GENRE_NAME, DU.GENDER, COUNT(DU.GENDER) AS CNT_GENDER FROM FACT_RATINGS FR JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID JOIN DIM_MOVIES DM ON FR.MOVIE_ID = DM.ID AND DM.GENRE_ACTION = 1      GROUP BY GENRE_NAME, GENDER UNION ALL
    SELECT 'Adventure'   AS GENRE_NAME, DU.GENDER, COUNT(DU.GENDER) AS CNT_GENDER FROM FACT_RATINGS FR JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID JOIN DIM_MOVIES DM ON FR.MOVIE_ID = DM.ID AND DM.GENRE_ADVENTURE = 1   GROUP BY GENRE_NAME, GENDER UNION ALL
    SELECT 'Animation'   AS GENRE_NAME, DU.GENDER, COUNT(DU.GENDER) AS CNT_GENDER FROM FACT_RATINGS FR JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID JOIN DIM_MOVIES DM ON FR.MOVIE_ID = DM.ID AND DM.GENRE_ANIMATION = 1   GROUP BY GENRE_NAME, GENDER UNION ALL
    SELECT 'Children'    AS GENRE_NAME, DU.GENDER, COUNT(DU.GENDER) AS CNT_GENDER FROM FACT_RATINGS FR JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID JOIN DIM_MOVIES DM ON FR.MOVIE_ID = DM.ID AND DM.GENRE_CHILDRENS = 1   GROUP BY GENRE_NAME, GENDER UNION ALL
    SELECT 'Comedy'      AS GENRE_NAME, DU.GENDER, COUNT(DU.GENDER) AS CNT_GENDER FROM FACT_RATINGS FR JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID JOIN DIM_MOVIES DM ON FR.MOVIE_ID = DM.ID AND DM.GENRE_COMEDY = 1      GROUP BY GENRE_NAME, GENDER UNION ALL
    SELECT 'Crime'       AS GENRE_NAME, DU.GENDER, COUNT(DU.GENDER) AS CNT_GENDER FROM FACT_RATINGS FR JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID JOIN DIM_MOVIES DM ON FR.MOVIE_ID = DM.ID AND DM.GENRE_CRIME = 1       GROUP BY GENRE_NAME, GENDER UNION ALL
    SELECT 'Documentary' AS GENRE_NAME, DU.GENDER, COUNT(DU.GENDER) AS CNT_GENDER FROM FACT_RATINGS FR JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID JOIN DIM_MOVIES DM ON FR.MOVIE_ID = DM.ID AND DM.GENRE_DOCUMENTARY = 1 GROUP BY GENRE_NAME, GENDER UNION ALL
    SELECT 'Drama'       AS GENRE_NAME, DU.GENDER, COUNT(DU.GENDER) AS CNT_GENDER FROM FACT_RATINGS FR JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID JOIN DIM_MOVIES DM ON FR.MOVIE_ID = DM.ID AND DM.GENRE_DRAMA = 1       GROUP BY GENRE_NAME, GENDER UNION ALL
    SELECT 'Fantasy'     AS GENRE_NAME, DU.GENDER, COUNT(DU.GENDER) AS CNT_GENDER FROM FACT_RATINGS FR JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID JOIN DIM_MOVIES DM ON FR.MOVIE_ID = DM.ID AND DM.GENRE_FANTASY = 1     GROUP BY GENRE_NAME, GENDER UNION ALL
    SELECT 'FilmNoir,'   AS GENRE_NAME, DU.GENDER, COUNT(DU.GENDER) AS CNT_GENDER FROM FACT_RATINGS FR JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID JOIN DIM_MOVIES DM ON FR.MOVIE_ID = DM.ID AND DM.GENRE_NOIR = 1        GROUP BY GENRE_NAME, GENDER UNION ALL
    SELECT 'Horror'      AS GENRE_NAME, DU.GENDER, COUNT(DU.GENDER) AS CNT_GENDER FROM FACT_RATINGS FR JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID JOIN DIM_MOVIES DM ON FR.MOVIE_ID = DM.ID AND DM.GENRE_HORROR = 1      GROUP BY GENRE_NAME, GENDER UNION ALL
    SELECT 'Musical'     AS GENRE_NAME, DU.GENDER, COUNT(DU.GENDER) AS CNT_GENDER FROM FACT_RATINGS FR JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID JOIN DIM_MOVIES DM ON FR.MOVIE_ID = DM.ID AND DM.GENRE_MUSICAL = 1     GROUP BY GENRE_NAME, GENDER UNION ALL
    SELECT 'Mystery'     AS GENRE_NAME, DU.GENDER, COUNT(DU.GENDER) AS CNT_GENDER FROM FACT_RATINGS FR JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID JOIN DIM_MOVIES DM ON FR.MOVIE_ID = DM.ID AND DM.GENRE_MYSTERY = 1     GROUP BY GENRE_NAME, GENDER UNION ALL
    SELECT 'Romance'     AS GENRE_NAME, DU.GENDER, COUNT(DU.GENDER) AS CNT_GENDER FROM FACT_RATINGS FR JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID JOIN DIM_MOVIES DM ON FR.MOVIE_ID = DM.ID AND DM.GENRE_ROMANCE = 1     GROUP BY GENRE_NAME, GENDER UNION ALL
    SELECT 'SciFi,'      AS GENRE_NAME, DU.GENDER, COUNT(DU.GENDER) AS CNT_GENDER FROM FACT_RATINGS FR JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID JOIN DIM_MOVIES DM ON FR.MOVIE_ID = DM.ID AND DM.GENRE_SCIFI = 1       GROUP BY GENRE_NAME, GENDER UNION ALL
    SELECT 'Thriller'    AS GENRE_NAME, DU.GENDER, COUNT(DU.GENDER) AS CNT_GENDER FROM FACT_RATINGS FR JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID JOIN DIM_MOVIES DM ON FR.MOVIE_ID = DM.ID AND DM.GENRE_THRILLER = 1    GROUP BY GENRE_NAME, GENDER UNION ALL
    SELECT 'War'         AS GENRE_NAME, DU.GENDER, COUNT(DU.GENDER) AS CNT_GENDER FROM FACT_RATINGS FR JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID JOIN DIM_MOVIES DM ON FR.MOVIE_ID = DM.ID AND DM.GENRE_WAR = 1         GROUP BY GENRE_NAME, GENDER UNION ALL
    SELECT 'Western'     AS GENRE_NAME, DU.GENDER, COUNT(DU.GENDER) AS CNT_GENDER FROM FACT_RATINGS FR JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID JOIN DIM_MOVIES DM ON FR.MOVIE_ID = DM.ID AND DM.GENRE_WESTERN = 1     GROUP BY GENRE_NAME, GENDER
)
GROUP BY GENRE_NAME;




