SELECT 
    DU.Occupation AS Occupation, 
    COUNT(FR.RATING) AS CNT_RATING 
FROM FACT_RATINGS FR
JOIN DIM_USERS DU ON FR.USER_ID = DU.USER_ID
GROUP BY DU.Occupation
ORDER BY CNT_RATING DESC
LIMIT 5;